### ISSUE TITLE
Drop nothing after 1.15 update

### ISSUE THREAD

**Issue by Craluminum2413** [copygirl/FarmlandDropsSoil#1]

**Comment by Craluminum2413** [comment]
Okay, it just make farmlands invisible after breaking. Grass can grow on these invisible farmlands

**Comment by copygirl** [comment]
There was an update to the game code that caused my code to throw an exception: `OriginalFertility` of farmland is no longer a single value for all nutrient types, but instead an array for each one separately. As a result, the block appears broken on the client, but is still present on the server. Causing the block to be re-sent (for example by trying to place one in its space or re-joining the world) would fix it.
